"""category added

Revision ID: 434dc0a692cd
Revises: 2fbe33f5a0e9
Create Date: 2025-10-22 20:56:50.279072

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '434dc0a692cd'
down_revision = '2fbe33f5a0e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
