"""products added

Revision ID: cb7e8c891295
Revises: e106a9ce284a
Create Date: 2025-10-23 15:10:46.574406

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cb7e8c891295'
down_revision = 'e106a9ce284a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
